import { base } from '$app/paths';
import { prop } from '$lib/wordle';

export const category = 'animatronic';

export const info = `
<p>
    Also includes animatronic-adjacent characters.
</p>
<p>Hard mode includes books, FNaF: HW hard mode, and FNaF: SD.</p>`;

const fnaf1 = prop('FNaF1', {
	full: "Five Nights at Freddy's",
	value: new Date('August 8, 2014'),
});
const fnaf2 = prop('FNaF2', {
	full: "Five Nights at Freddy's 2",
	value: new Date('November 11, 2014'),
});
const fnaf3 = prop('FNaF3', {
	full: "Five Nights at Freddy's 3",
	value: new Date('March 2, 2015'),
});
const fnaf4 = prop('FNaF4', {
	full: "Five Nights at Freddy's 4",
	value: new Date('July 23, 2015'),
});
const he = prop('FNaF4: HE', {
	full: "Five Nights at Freddy's 4: Halloween Edition",
	value: new Date('October 30, 2015'),
});
const fw = prop('FW', {
	full: 'FNaF World',
	value: new Date('January 21, 2016'),
});
const sl = prop('FNaF: SL', {
	full: "Five Nights at Freddy's: Sister Location",
	value: new Date('October 7, 2016'),
});
const ffps = prop('FFPS', {
	full: "Freddy Fazbear Frights #1Fazbear's Pizzeria Simulator",
	value: new Date('December 4, 2017'),
});
const ucn = prop('UCN', {
	full: 'Ultimate Custom Night',
	value: new Date('June 27, 2018'),
});
const hw = prop('FNaF: HW', {
	full: "Five Nights at Freddy's: Help Wanted",
	value: new Date('May 28, 2019'),
});
const cod = prop('CoD', {
	full: "Five Nights at Freddy's: Help Wanted - Curse of Dreadbear",
	value: new Date('October 23, 2019'),
});
const sd = prop('FNaF: SD', {
	full: "Five Nights at Freddy's AR: Special Delivery",
	value: new Date('November 25, 2019'),
});
const sb = prop('FNaF: SB', {
	full: "Five Nights at Freddy's: Security Breach",
	value: new Date('December 16, 2021'),
});
const ruin = prop('RUIN', {
	full: "Five Nights at Freddy's: Security Breach - RUIN",
	value: new Date('July 25, 2023'),
});
const hw2 = prop('FNaF: HW2', {
	full: "Five Nights at Freddy's: Help Wanted 2",
	value: new Date('December 14, 2023'),
});
// const itp = prop('FNaF: ItP', {
// 	full: "Five Nights at Freddy's: Into the Pit",
// 	value: new Date('August 7, 2024'),
// });
// const sotm = prop('FNaF: SotM', {
// 	full: "Five Nights at Freddy's: Secret of the Mimic",
// 	value: new Date('2025'),
// });

const tse = prop('TSE', {
	full: "Five Nights at Freddy's: The Silver Eyes",
	value: new Date('December 17, 2015'),
});
const tto = prop('TTO', {
	full: "Five Nights at Freddy's: The Twisted Ones",
	value: new Date('June 27, 2017'),
});
const tfc = prop('TFC', {
	full: "Five Nights at Freddy's: The Fourth Closet",
	value: new Date('June 26, 2018'),
});
const trilogy = [tse, tto, tfc];

const ff1 = prop('FF1', {
	full: 'Fazbear Frights #1',
	value: new Date('December 26, 2019'),
});
const ff2 = prop('FF2', {
	full: 'Fazbear Frights #2',
	value: new Date('March 3, 2020'),
});
const ff3 = prop('FF3', {
	full: 'Fazbear Frights #3',
	value: new Date('May 5, 2020'),
});
const ff4 = prop('FF4', {
	full: 'Fazbear Frights #4',
	value: new Date('July 7, 2020'),
});
const ff5 = prop('FF5', {
	full: 'Fazbear Frights #5',
	value: new Date('September 1, 2020'),
});
const ff6 = prop('FF6', {
	full: 'Fazbear Frights #6',
	value: new Date('December 29, 2020'),
});
const ff7 = prop('FF7', {
	full: 'Fazbear Frights #7',
	value: new Date('March 2, 2021'),
});
const ff8 = prop('FF8', {
	full: 'Fazbear Frights #8',
	value: new Date('May 4, 2021'),
});
const ff9 = prop('FF9', {
	full: 'Fazbear Frights #9',
	value: new Date('July 6, 2021'),
});
const ff10 = prop('FF10', {
	full: 'Fazbear Frights #10',
	value: new Date('September 7, 2021'),
});
const ff11 = prop('FF11', {
	full: 'Fazbear Frights #11',
	value: new Date('November 2, 2021'),
});
const ff12 = prop('FF12', {
	full: 'Fazbear Frights #12',
	value: new Date('April 19, 2022'),
});
const frights = [ff1, ff2, ff3, ff4, ff5, ff6, ff7, ff8, ff9, ff10, ff11, ff12];

const tftp1 = prop('TftP1', {
	full: 'Tales from the Pizzaplex #1',
	value: new Date('July 19, 2022'),
});
const tftp2 = prop('TftP2', {
	full: 'Tales from the Pizzaplex #2',
	value: new Date('September 20, 2022'),
});
const tftp3 = prop('TftP3', {
	full: 'Tales from the Pizzaplex #3',
	value: new Date('December 6, 2022'),
});
const tftp4 = prop('TftP4', {
	full: 'Tales from the Pizzaplex #4',
	value: new Date('December 27, 2022'),
});
const tftp5 = prop('TftP5', {
	full: 'Tales from the Pizzaplex #5',
	value: new Date('March 7, 2023'),
});
const tftp6 = prop('TftP6', {
	full: 'Tales from the Pizzaplex #6',
	value: new Date('May 2, 2023'),
});
const tftp7 = prop('TftP7', {
	full: 'Tales from the Pizzaplex #7',
	value: new Date('July 18, 2023'),
});
const tftp8 = prop('TftP8', {
	full: 'Tales from the Pizzaplex #8',
	value: new Date('October 3, 2023'),
});
const tales = [tftp1, tftp2, tftp3, tftp4, tftp5, tftp6, tftp7, tftp8];

const hard = {
	'8-Bit Baby': {
		src: `${base}/freddle/icons/8-bit-baby.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['White', 'Red'],
		eyeColor: 'Green',
		debut: sd,
	},
	'Aeronaut Toy Freddy': {
		src: `${base}/freddle/icons/aeronaut-toy-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Blue',
		debut: sd,
	},
	'Arctic Ballora': {
		src: `${base}/freddle/icons/arctic-ballora.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: 'Blue',
		eyeColor: 'Blue',
		debut: sd,
	},
	'Balloon Boy': {
		src: `${base}/freddle/icons/bb.webp`,
		aliases: ['bb'],
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['Peach', 'Blue', 'Red'],
		eyeColor: 'Blue',
		debut: fnaf2,
	},
	Ballora: {
		src: `${base}/freddle/icons/ballora.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['White', 'Blue'],
		eyeColor: ['Pink', 'Purple'],
		debut: sl,
	},
	Bidybab: {
		src: `${base}/freddle/icons/bidybab.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: 'Peach',
		eyeColor: ['Purple', 'Green'],
		debut: sl,
	},
	'Big Bad Foxy': {
		src: `${base}/freddle/icons/big-bad-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: ['Red', 'Black'],
		eyeColor: ['Black', 'Red'],
		debut: sd,
	},
	'Black Heart Bonnie': {
		src: `${base}/freddle/icons/black-heart-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: ['Black', 'Red'],
		eyeColor: 'Red',
		debut: sd,
	},
	'Black Ice Freddy Frostbear': {
		src: `${base}/freddle/icons/black-ice-freddy-frostbear.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Blue',
		eyeColor: 'Blue',
		debut: sd,
	},
	'Bon-Bon': {
		src: `${base}/freddle/icons/bon-bon.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Blue',
		eyeColor: 'Purple',
		debut: sl,
	},
	Bonnet: {
		src: `${base}/freddle/icons/bonnet.webp`,
		pronouns: 'She/Her',
		model: 'Rabbit',
		mainColors: 'Pink',
		eyeColor: 'Green',
		debut: sl,
	},
	Bonnie: {
		src: `${base}/freddle/icons/bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Purple',
		eyeColor: 'Purple',
		debut: fnaf1,
	},
	'Boulder Toy Bonnie': {
		src: `${base}/freddle/icons/boulder-toy-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: ['Gray', 'Green'],
		eyeColor: 'N/A',
		debut: sd,
	},
	'Broiler Baby': {
		src: `${base}/freddle/icons/broiler-baby.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['Gray', 'Brown'],
		eyeColor: 'Red',
		debut: sd,
	},
	'Bucket Bob': {
		src: `${base}/freddle/icons/bucket-bob.webp`,
		aliases: ['trash and the gang'],
		pronouns: 'He/Him',
		model: 'Bucket',
		mainColors: ['Gray', 'Brown'],
		eyeColor: 'Black',
		debut: ffps,
	},
	'Burnt Foxy': {
		src: `${base}/freddle/icons/burnt-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Brown',
		eyeColor: 'Orange',
		debut: hw,
	},
	Burntrap: {
		src: `${base}/freddle/icons/burntrap.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: ['Green', 'Gray'],
		eyeColor: 'Purple',
		debut: sb,
	},
	'Candy Cadet': {
		src: `${base}/freddle/icons/candy-cadet.webp`,
		pronouns: 'He/Him',
		model: 'Other',
		mainColors: 'Gray',
		eyeColor: 'N/A',
		debut: ffps,
	},
	'Captain Foxy': {
		src: `${base}/freddle/icons/captain-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: ['Red', 'Blue'],
		eyeColor: 'Yellow',
		debut: cod,
	},
	'Catrina Toy Chica': {
		src: `${base}/freddle/icons/catrina-toy-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: ['White', 'Red'],
		eyeColor: 'Red',
		debut: sd,
	},
	'Caution Bot': {
		src: `${base}/freddle/icons/caution-bot.webp`,
		aliases: ['wet floor bot'],
		pronouns: 'It/Its',
		model: 'Wet Floor Sign',
		mainColors: 'Yellow',
		eyeColor: 'Yellow',
		debut: sb,
	},
	'Charlotte Emily': {
		src: `${base}/freddle/icons/charlie.webp`,
		aliases: ['charlie'],
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: 'Peach',
		eyeColor: 'Brown',
		debut: tse,
	},
	Chica: {
		src: `${base}/freddle/icons/chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: 'Yellow',
		eyeColor: 'Purple',
		debut: fnaf1,
	},
	'Chocolate Bonnie': {
		src: `${base}/freddle/icons/chocolate-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Brown',
		eyeColor: 'Orange',
		debut: sd,
	},
	'Circus Baby': {
		src: `${base}/freddle/icons/circus-baby.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['White', 'Red'],
		eyeColor: ['Blue', 'Green'],
		debut: fw,
	},
	'Clockwork Ballora': {
		src: `${base}/freddle/icons/clockwork-ballora.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: 'Yellow',
		eyeColor: 'Blue',
		debut: sd,
	},
	'Clockwork Minireena': {
		src: `${base}/freddle/icons/clockwork-minireena.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['Brown', 'White'],
		eyeColor: 'Green',
		debut: sd,
	},
	'Clown Springtrap': {
		src: `${base}/freddle/icons/clown-springtrap.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: ['White', 'Red'],
		eyeColor: ['Blue', 'Pink'],
		debut: sd,
	},
	'Coils the Birthday Clown': {
		src: `${base}/freddle/icons/coils.webp`,
		aliases: ['coils'],
		pronouns: 'It/Its',
		model: 'Humanoid',
		mainColors: ['White', 'Red', 'Green'],
		eyeColor: 'Green',
		debut: ff9,
	},
	'Dark Foxy': {
		src: `${base}/freddle/icons/dark-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Gray',
		eyeColor: 'White',
		debut: hw,
	},
	'Dark Freddy': {
		src: `${base}/freddle/icons/dark-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Black',
		eyeColor: 'White',
		debut: hw,
	},
	'Dark Water Endo': {
		src: `${base}/freddle/icons/dark-water-endo.webp`,
		pronouns: 'Unknown',
		model: 'Endoskeleton',
		mainColors: ['Blue', 'White'],
		eyeColor: 'White',
		debut: sd,
	},
	'Dee Dee': {
		src: `${base}/freddle/icons/dee-dee.webp`,
		aliases: ['dd'],
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['Peach', 'Pink', 'Orange'],
		eyeColor: 'Green',
		debut: ucn,
	},
	'DJ Music Man': {
		src: `${base}/freddle/icons/dj-music-man.webp`,
		pronouns: 'He/Him',
		model: 'Other',
		mainColors: 'White',
		eyeColor: 'Black',
		debut: sb,
	},
	Dreadbear: {
		src: `${base}/freddle/icons/dreadbear.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Gray',
		eyeColor: 'Yellow',
		debut: cod,
	},
	'Easter Bonnie': {
		src: `${base}/freddle/icons/easter-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'White',
		eyeColor: 'Blue',
		debut: sd,
	},
	Eclipse: {
		src: `${base}/freddle/icons/eclipse.webp`,
		aliases: ['daycare attendant'],
		pronouns: 'They/Them',
		model: 'Humanoid',
		mainColors: ['Gray', 'Yellow', 'Blue'],
		eyeColor: ['Yellow', 'Red'],
		debut: sb,
	},
	'Egg Baby': {
		src: `${base}/freddle/icons/egg-baby.webp`,
		pronouns: 'It/Its',
		model: 'Humanoid',
		mainColors: ['Peach', 'Blue'],
		eyeColor: 'Black',
		debut: ffps,
	},
	'El Chip': {
		src: `${base}/freddle/icons/el-chip.webp`,
		pronouns: 'He/Him',
		model: 'Beaver',
		mainColors: 'Brown',
		eyeColor: 'Green',
		debut: ffps,
	},
	Eleanor: {
		src: `${base}/freddle/icons/eleanor.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['White', 'Red'],
		eyeColor: 'Green',
		debut: ff1,
	},
	Electrobab: {
		src: `${base}/freddle/icons/electrobab.webp`,
		pronouns: 'They/Them',
		model: 'Humanoid',
		mainColors: 'Peach',
		eyeColor: 'Yellow',
		debut: sl,
	},
	Ella: {
		src: `${base}/freddle/icons/ella.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['Peach', 'Blue', 'Pink'],
		eyeColor: 'Blue',
		debut: tse,
	},
	'Endo-01': {
		src: `${base}/freddle/icons/endo-01.webp`,
		aliases: ['bare endo'],
		pronouns: 'it/its',
		model: 'Endoskeleton',
		mainColors: 'Gray',
		eyeColor: 'Blue',
		debut: fnaf1,
	},
	'Endo-02': {
		src: `${base}/freddle/icons/endo-02.webp`,
		pronouns: 'it/its',
		model: 'Endoskeleton',
		mainColors: 'Gray',
		eyeColor: 'Blue',
		debut: fnaf2,
	},
	Ennard: {
		src: `${base}/freddle/icons/ennard.webp`,
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['Gray', 'White'],
		eyeColor: 'Blue',
		debut: sl,
	},
	Fetch: {
		src: `${base}/freddle/icons/fetch.webp`,
		pronouns: 'He/Him',
		model: 'Canine',
		mainColors: 'Gray',
		eyeColor: 'Orange',
		debut: ff2,
	},
	'Firework Freddy': {
		src: `${base}/freddle/icons/firework-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: ['Brown', 'Blue', 'Red'],
		eyeColor: 'Blue',
		debut: sd,
	},
	'Flamethrower Endo': {
		src: `${base}/freddle/icons/flamethrower-endo.webp`,
		pronouns: 'It/Its',
		model: 'Endoskeleton',
		mainColors: ['Yellow', 'Brown'],
		eyeColor: 'Blue',
		debut: sd,
	},
	'Flaming Springtrap': {
		src: `${base}/freddle/icons/flaming-springtrap.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: ['Black', 'Orange'],
		eyeColor: 'Red',
		debut: sd,
	},
	Foxy: {
		src: `${base}/freddle/icons/foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Red',
		eyeColor: 'Yellow',
		debut: fnaf1,
	},
	Fredbear: {
		src: `${base}/freddle/icons/fredbear.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Yellow',
		eyeColor: ['Black', 'White'],
		debut: fnaf3,
	},
	Freddles: {
		src: `${base}/freddle/icons/freddles.webp`,
		pronouns: 'They/Them',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: ['Black', 'White'],
		debut: fnaf4,
	},
	'Freddy Fazbear': {
		src: `${base}/freddle/icons/freddy.webp`,
		aliases: ['har har har har har', 'freddy'],
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Blue',
		debut: fnaf1,
	},
	'Frost Plushtrap': {
		src: `${base}/freddle/icons/frost-plushtrap.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Blue',
		eyeColor: 'Blue',
		debut: sd,
	},
	'Frostbite Balloon Boy': {
		src: `${base}/freddle/icons/frostbite-bb.webp`,
		aliases: ['blizzard balloon boy', 'blizzard bb', 'frostbite bb'],
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['White', 'Blue'],
		eyeColor: 'N/A',
		debut: sd,
	},
	'Fruit Punch Clown': {
		src: `${base}/freddle/icons/fruit-punch-clown.webp`,
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['White', 'Red', 'Purple'],
		eyeColor: 'Green',
		debut: ffps,
	},
	'Funtime Chica': {
		src: `${base}/freddle/icons/funtime-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: ['White', 'Pink'],
		eyeColor: 'Pink',
		debut: ffps,
	},
	'Funtime Foxy': {
		src: `${base}/freddle/icons/funtime-foxy.webp`,
		pronouns: 'Yes',
		model: 'Fox',
		mainColors: ['White', 'Pink'],
		eyeColor: 'Yellow',
		debut: fw,
	},
	'Funtime Freddy': {
		src: `${base}/freddle/icons/funtime-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: ['White', 'Purple'],
		eyeColor: 'Blue',
		debut: sl,
	},
	'Glamrock Bonnie': {
		src: `${base}/freddle/icons/glamrock-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: ['Blue', 'Red'],
		eyeColor: 'Red',
		debut: ruin,
	},
	'Glamrock Chica': {
		src: `${base}/freddle/icons/glamrock-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: ['White', 'Purple', 'Green'],
		eyeColor: 'Blue',
		debut: sb,
	},
	'Glamrock Endo': {
		src: `${base}/freddle/icons/glamrock-endo.webp`,
		pronouns: 'He/Him',
		model: 'Endoskeleton',
		mainColors: 'Gray',
		eyeColor: 'Red',
		debut: sb,
	},
	'Glamrock Freddy': {
		src: `${base}/freddle/icons/glamrock-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Orange',
		eyeColor: 'Blue',
		debut: sb,
	},
	'Glamrock Mr. Hippo': {
		src: `${base}/freddle/icons/glamrock-mr-hippo.webp`,
		pronouns: 'He/Him',
		model: 'Hippo',
		mainColors: 'Purple',
		eyeColor: 'Blue',
		debut: sb,
	},
	Glitchtrap: {
		src: `${base}/freddle/icons/glitchtrap.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Brown',
		eyeColor: 'Purple',
		debut: hw,
	},
	'Golden Freddy': {
		src: `${base}/freddle/icons/golden-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Yellow',
		eyeColor: 'N/A',
		debut: fnaf1,
	},
	'Grimm Foxy': {
		src: `${base}/freddle/icons/grimm-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Orange',
		eyeColor: 'Orange',
		debut: cod,
	},
	HandUnit: {
		src: `${base}/freddle/icons/hand-unit.webp`,
		pronouns: 'He/Him',
		model: 'Other',
		mainColors: 'Yellow',
		eyeColor: 'Black',
		debut: sl,
	},
	'Happy Frog': {
		src: `${base}/freddle/icons/happy-frog.webp`,
		pronouns: 'She/Her',
		model: 'Frog',
		mainColors: ['Green', 'Yellow'],
		eyeColor: 'Pink',
		debut: ffps,
	},
	'Heartsick Baby': {
		src: `${base}/freddle/icons/heartsick-baby.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['Purple', 'White'],
		eyeColor: 'Red',
		debut: sd,
	},
	Helpi: {
		src: `${base}/freddle/icons/helpi.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: ['Purple', 'Blue'],
		eyeColor: 'Blue',
		debut: ruin,
	},
	Helpy: {
		src: `${base}/freddle/icons/helpy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: ['White', 'Purple'],
		eyeColor: 'Blue',
		debut: ffps,
	},
	'Highscore Toy Chica': {
		src: `${base}/freddle/icons/highscore-toy-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: ['Blue', 'Black'],
		eyeColor: 'Yellow',
		debut: sd,
	},
	'Jack-O-Bonnie': {
		src: `${base}/freddle/icons/jack-o-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: ['Orange', 'Brown'],
		eyeColor: 'N/A',
		debut: he,
	},
	'Jack-O-Chica': {
		src: `${base}/freddle/icons/jack-o-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: ['Orange', 'Brown'],
		eyeColor: 'N/A',
		debut: he,
	},
	'Jetpack Balloon Boy': {
		src: `${base}/freddle/icons/jetpack-balloon-boy.webp`,
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: 'Brown',
		eyeColor: 'Orange',
		debut: sd,
	},
	JJ: {
		src: `${base}/freddle/icons/jj.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['Peach', 'Blue', 'Purple'],
		eyeColor: 'Pink',
		debut: fnaf2,
	},
	Lefty: {
		src: `${base}/freddle/icons/lefty.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Black',
		eyeColor: ['Yellow', 'Black'],
		debut: ffps,
	},
	'Lemonade Clown': {
		src: `${base}/freddle/icons/lemonade-clown.webp`,
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['White', 'Purple', 'Orange'],
		eyeColor: 'Blue',
		debut: ffps,
	},
	'Liberty Chica': {
		src: `${base}/freddle/icons/liberty-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: 'Blue',
		eyeColor: 'Green',
		debut: sd,
	},
	'Little Red Chica': {
		src: `${base}/freddle/icons/little-red-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: ['Red', 'White'],
		eyeColor: 'Yellow',
		debut: sd,
	},
	Lolbit: {
		src: `${base}/freddle/icons/lolbit.webp`,
		pronouns: 'they/them',
		model: 'Fox',
		mainColors: ['White', 'Orange', 'Purple'],
		eyeColor: 'White',
		debut: sl,
	},
	'Lonely Freddy': {
		src: `${base}/freddle/icons/lonely-freddy.webp`,
		pronouns: 'it/its',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Blue',
		debut: ff2,
	},
	'Lucky Boy': {
		src: `${base}/freddle/icons/lucky-boy.webp`,
		pronouns: 'He/Him',
		model: 'Blue',
		mainColors: ['Peach', 'Blue', 'Red'],
		eyeColor: 'Blue',
		debut: ff8,
	},
	'Magician Mangle': {
		src: `${base}/freddle/icons/magician-mangle.webp`,
		pronouns: 'Yes',
		model: 'Fox',
		mainColors: 'White',
		eyeColor: ['Blue', 'Yellow'],
		debut: sd,
	},
	Mangle: {
		src: `${base}/freddle/icons/mangle.webp`,
		pronouns: 'Yes',
		model: 'Fox',
		mainColors: ['White', 'Pink'],
		eyeColor: 'Yellow',
		debut: fnaf2,
	},
	'Mask Bot': {
		src: `${base}/freddle/icons/mask-bot.webp`,
		pronouns: 'Unknown',
		model: 'Humanoid',
		mainColors: ['White', 'Yellow'],
		eyeColor: 'Black',
		debut: ruin,
	},
	'Melted Chocolate Bonnie': {
		src: `${base}/freddle/icons/melted-chocolate-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Brown',
		eyeColor: 'Orange',
		debut: sd,
	},
	'Mini Music Man': {
		src: `${base}/freddle/icons/mini-music-man.webp`,
		pronouns: 'He/Him',
		model: 'Other',
		mainColors: ['White', 'Purple', 'Pink'],
		eyeColor: 'Black',
		debut: sb,
	},
	Minireena: {
		src: `${base}/freddle/icons/minireena.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['Brown', 'White'],
		eyeColor: 'Yellow',
		debut: sl,
	},
	'Molten Freddy': {
		src: `${base}/freddle/icons/molten-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: ['Gray', 'White', 'Brown'],
		eyeColor: 'Orange',
		debut: ffps,
	},
	'Montgomery Gator': {
		src: `${base}/freddle/icons/monty.webp`,
		aliases: ['monty'],
		pronouns: 'He/Him',
		model: 'Alligator',
		mainColors: ['Green', 'Purple'],
		eyeColor: 'Red',
		debut: sb,
	},
	Moon: {
		src: `${base}/freddle/icons/moon.webp`,
		aliases: ['daycare attendant'],
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['Blue', 'White', 'Black'],
		eyeColor: 'Red',
		debut: sb,
	},
	'Mr. Can-Do': {
		src: `${base}/freddle/icons/mr-can-do.webp`,
		aliases: ['trash and the gang'],
		pronouns: 'He/Him',
		model: 'Other',
		mainColors: ['Red', 'Gray'],
		eyeColor: 'Black',
		debut: ffps,
	},
	'Mr. Hippo': {
		src: `${base}/freddle/icons/mr-hippo.webp`,
		pronouns: 'He/Him',
		model: 'Hippo',
		mainColors: 'Purple',
		eyeColor: 'Blue',
		debut: ffps,
	},
	'Mr. Hugs': {
		src: `${base}/freddle/icons/mr-hugs.webp`,
		aliases: ['trash and the gang'],
		pronouns: 'He/Him',
		model: 'Vacuum',
		mainColors: ['Green', 'Brown'],
		eyeColor: 'Black',
		debut: ffps,
	},
	'Music Man': {
		src: `${base}/freddle/icons/music-man.webp`,
		pronouns: 'He/Him',
		model: 'Other',
		mainColors: ['White', 'Purple', 'Pink'],
		eyeColor: 'Black',
		debut: ffps,
	},
	'Mystic Hippo': {
		src: `${base}/freddle/icons/mystic-hippo.webp`,
		pronouns: 'She/Her',
		model: 'Hippo',
		mainColors: 'Purple',
		eyeColor: 'Blue',
		debut: hw2,
	},
	'Nedd Bear': {
		src: `${base}/freddle/icons/nedd-bear.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Green',
		debut: ffps,
	},
	'Neon Bonnie': {
		src: `${base}/freddle/icons/neon-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: ['Black'],
		eyeColor: 'Blue',
		debut: hw,
	},
	'Neon Chica': {
		src: `${base}/freddle/icons/neon-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: ['Black'],
		eyeColor: 'Green',
		debut: hw,
	},
	Nightmare: {
		src: `${base}/freddle/icons/nightmare.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Black',
		eyeColor: 'Red',
		debut: fnaf4,
	},
	'Nightmare Balloon Boy': {
		src: `${base}/freddle/icons/nightmare-bb.webp`,
		aliases: ['nightmare bb'],
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['Peach', 'Red', 'Purple'],
		eyeColor: 'Red',
		debut: he,
	},
	'Nightmare Bonnie': {
		src: `${base}/freddle/icons/nightmare-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Blue',
		eyeColor: ['Purple', 'Yellow'],
		debut: fnaf4,
	},
	'Nightmare Chica': {
		src: `${base}/freddle/icons/nightmare-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: 'Yellow',
		eyeColor: ['Blue', 'Red'],
		debut: fnaf4,
	},
	'Nightmare Endo': {
		src: `${base}/freddle/icons/nightmare-endo.webp`,
		pronouns: 'Unknown',
		model: 'Endoskeleton',
		mainColors: 'Gray',
		eyeColor: 'Red',
		debut: hw,
	},
	'Nightmare Foxy': {
		src: `${base}/freddle/icons/nightmare-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Red',
		eyeColor: 'Orange',
		debut: fnaf4,
	},
	'Nightmare Fredbear': {
		src: `${base}/freddle/icons/nightmare-fredbear.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Yellow',
		eyeColor: 'Red',
		debut: fnaf4,
	},
	'Nightmare Freddy': {
		src: `${base}/freddle/icons/nightmare-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Orange',
		debut: fnaf4,
	},
	'Nightmare Mangle': {
		src: `${base}/freddle/icons/nightmare-mangle.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: ['White', 'Pink'],
		eyeColor: 'Yellow',
		debut: he,
	},
	Nightmarionne: {
		src: `${base}/freddle/icons/nightmarionne.webp`,
		aliases: ['nightmare puppet'],
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['Black', 'White'],
		eyeColor: ['Black', 'White'],
		debut: he,
	},
	'Nightmarionne S.T.A.F.F. Bot': {
		src: `${base}/freddle/icons/nightmarionne-staff-bot.webp`,
		pronouns: 'Unknown',
		model: 'Humanoid',
		mainColors: ['White', 'Black'],
		eyeColor: 'White',
		debut: he,
	},
	'No. 1 Crate': {
		src: `${base}/freddle/icons/no-1-crate.webp`,
		aliases: ['trash and the gang'],
		pronouns: 'She/Her',
		model: 'Crate',
		mainColors: ['Blue', 'Red'],
		eyeColor: 'Black',
		debut: ffps,
	},
	'Old Man Consequences': {
		src: `${base}/freddle/icons/omc.webp`,
		aliases: ['omc'],
		pronouns: 'He/Him',
		model: 'Alligator',
		mainColors: 'Red',
		eyeColor: 'N/A',
		debut: fw,
	},
	'Orville Elephant': {
		src: `${base}/freddle/icons/orville-elephant.webp`,
		pronouns: 'He/Him',
		model: 'Elephant',
		mainColors: 'Orange',
		eyeColor: 'Blue',
		debut: ffps,
	},
	'Pan Stan': {
		src: `${base}/freddle/icons/pan-stan.webp`,
		aliases: ['trash and the gang'],
		pronouns: 'He/Him',
		model: 'Pan',
		mainColors: ['Gray', 'Brown'],
		eyeColor: 'Black',
		debut: ffps,
	},
	'Party Freddy': {
		src: `${base}/freddle/icons/party-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: ['Black', 'Red'],
		eyeColor: 'Black',
		debut: hw,
	},
	'Phantom Balloon Boy': {
		src: `${base}/freddle/icons/phantom-bb.webp`,
		aliases: ['phantom bb'],
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: 'Green',
		eyeColor: ['Black', 'White'],
		debut: fnaf3,
	},
	'Phantom Chica': {
		src: `${base}/freddle/icons/phantom-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: 'Green',
		eyeColor: ['Black', 'White'],
		debut: fnaf3,
	},
	'Phantom Foxy': {
		src: `${base}/freddle/icons/phantom-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Green',
		eyeColor: ['Black', 'White'],
		debut: fnaf3,
	},
	'Phantom Freddy': {
		src: `${base}/freddle/icons/phantom-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Green',
		eyeColor: ['Black', 'White'],
		debut: fnaf3,
	},
	'Phantom Mangle': {
		src: `${base}/freddle/icons/phantom-mangle.webp`,
		pronouns: 'Yes',
		model: 'Fox',
		mainColors: 'Green',
		eyeColor: ['Black', 'White'],
		debut: fnaf3,
	},
	'Phantom Puppet': {
		src: `${base}/freddle/icons/phantom-puppet.webp`,
		aliases: ['phantom marionette'],
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: 'Green',
		eyeColor: ['Black', 'White'],
		debut: fnaf3,
	},
	Pigpatch: {
		src: `${base}/freddle/icons/pigpatch.webp`,
		pronouns: 'He/Him',
		model: 'Pig',
		mainColors: 'Pink',
		eyeColor: ['Green', 'Blue'],
		debut: ffps,
	},
	'Piranha Plushtrap': {
		src: `${base}/freddle/icons/piranha-plushtrap.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Gray',
		eyeColor: 'Blue',
		debut: sd,
	},
	Plushtrap: {
		src: `${base}/freddle/icons/plushtrap.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: ['Green', 'Brown'],
		eyeColor: 'Black',
		debut: fnaf4,
	},
	'Prize King': {
		src: `${base}/freddle/icons/prize-king.webp`,
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['Yellow'],
		eyeColor: 'Green',
		debut: ffps,
	},
	'The Puppet': {
		src: `${base}/freddle/icons/puppet.webp`,
		aliases: ['the marionette'],
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['Black', 'White'],
		eyeColor: ['Black', 'White'],
		debut: fnaf2,
	},
	'Radioactive Foxy': {
		src: `${base}/freddle/icons/radioactive-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Green',
		eyeColor: 'Yellow',
		debut: sd,
	},
	Ralpho: {
		src: `${base}/freddle/icons/ralpho.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Orange',
		eyeColor: 'Blue',
		debut: ff5,
	},
	'Ringmaster Foxy': {
		src: `${base}/freddle/icons/ringmaster-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: ['White', 'Red'],
		eyeColor: 'Yellow',
		debut: sd,
	},
	'Rockstar Bonnie': {
		src: `${base}/freddle/icons/rockstar-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Blue',
		eyeColor: 'Green',
		debut: ffps,
	},
	'Rockstar Chica': {
		src: `${base}/freddle/icons/rockstar-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: 'Yellow',
		eyeColor: 'Pink',
		debut: ffps,
	},
	'Rockstar Foxy': {
		src: `${base}/freddle/icons/rockstar-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Red',
		eyeColor: 'Orange',
		debut: ffps,
	},
	'Rockstar Freddy': {
		src: `${base}/freddle/icons/rockstar-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Blue',
		debut: ffps,
	},
	'Roxanne Wolf': {
		src: `${base}/freddle/icons/roxy.webp`,
		aliases: ['roxy'],
		pronouns: 'She/Her',
		model: 'Canine',
		mainColors: ['Gray', 'Purple'],
		eyeColor: 'Yellow',
		debut: sb,
	},
	RWQFSFASXC: {
		src: `${base}/freddle/icons/rwqfsfasxc.webp`,
		aliases: ['shadow bonnie'],
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Black',
		eyeColor: 'White',
		debut: fnaf2,
	},
	'Scorching Chica': {
		src: `${base}/freddle/icons/scorching-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: ['Black', 'Red'],
		eyeColor: 'Orange',
		debut: sd,
	},
	'Scrap Baby': {
		src: `${base}/freddle/icons/scrap-baby.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['Orange', 'White'],
		eyeColor: 'Green',
		debut: ffps,
	},
	Scraptrap: {
		src: `${base}/freddle/icons/scraptrap.webp`,
		aliases: ['william afton'],
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Green',
		eyeColor: 'Gray',
		debut: ffps,
	},
	'Security Puppet': {
		src: `${base}/freddle/icons/security-puppet.webp`,
		pronouns: 'It/Its',
		model: 'Humanoid',
		mainColors: ['Black', 'White'],
		eyeColor: 'Yellow',
		debut: ffps,
	},
	'Serpent Mangle': {
		src: `${base}/freddle/icons/serpent-mangle.webp`,
		pronouns: 'Yes',
		model: 'Fox',
		mainColors: ['Green', 'Yellow', 'Red'],
		eyeColor: 'Yellow',
		debut: sd,
	},
	'Shadow Freddy': {
		src: `${base}/freddle/icons/shadow-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Purple',
		eyeColor: 'White',
		debut: fnaf2,
	},
	'Shadow Mangle': {
		src: `${base}/freddle/icons/shadow-mangle.webp`,
		pronouns: 'yes',
		model: 'Fox',
		mainColors: 'Black',
		eyeColor: 'Yellow',
		debut: hw,
	},
	'Shamrock Freddy': {
		src: `${base}/freddle/icons/shamrock-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Green',
		eyeColor: 'Green',
		debut: sd,
	},
	'Spring Bonnie': {
		src: `${base}/freddle/icons/spring-bonnie.webp`,
		pronouns: 'They/Them',
		model: 'Rabbit',
		mainColors: 'Yellow',
		eyeColor: 'Green',
		debut: fnaf3,
	},
	Springtrap: {
		src: `${base}/freddle/icons/springtrap.webp`,
		aliases: ['william afton'],
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Green',
		eyeColor: 'Gray',
		debut: fnaf3,
	},
	Stanley: {
		src: `${base}/freddle/icons/stanley.webp`,
		pronouns: 'He/Him',
		model: 'Other',
		mainColors: 'White',
		eyeColor: 'Purple',
		debut: tse,
	},
	'The Stitchwraith': {
		src: `${base}/freddle/icons/stitchwraith.webp`,
		pronouns: 'It/Its',
		model: 'Endoskeleton',
		mainColors: ['Black', 'White'],
		eyeColor: ['Black', 'White'],
		debut: ff1,
	},
	Sun: {
		src: `${base}/freddle/icons/sun.webp`,
		aliases: ['daycare attendant'],
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: 'Yellow',
		eyeColor: 'White',
		debut: sb,
	},
	'Sunken Toy Bonnie': {
		src: `${base}/freddle/icons/sunken-toy-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: ['Brown', 'Green'],
		eyeColor: ['Blue', 'Purple'],
		debut: sd,
	},
	'Swamp Balloon Boy': {
		src: `${base}/freddle/icons/swamp-bb.webp`,
		aliases: ['swamp bb'],
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['Brown', 'Green', 'Gray'],
		eyeColor: 'N/A',
		debut: sd,
	},
	'System Error Toy Bonnie': {
		src: `${base}/freddle/icons/system-error-toy-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Red',
		eyeColor: 'Yellow',
		debut: sd,
	},
	'Tag-Along Freddy': {
		src: `${base}/freddle/icons/tag-along-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Blue',
		debut: ff7,
	},
	Tangle: {
		src: `${base}/freddle/icons/tangle.webp`,
		aliases: ['the blob'],
		pronouns: 'It/Its',
		model: 'Bear',
		mainColors: 'Gray',
		eyeColor: 'Red',
		debut: sb,
	},
	'The Curse': {
		src: `${base}/freddle/icons/the-curse.webp`,
		pronouns: 'he/him',
		model: 'Rabbit',
		mainColors: ['Blue', 'Yellow', 'Green'],
		eyeColor: 'Yellow',
		debut: sd,
	},
	'The Entity': {
		src: `${base}/freddle/icons/mxes.webp`,
		aliases: ['m.x.e.s.', 'mxes'],
		pronouns: 'They/Them',
		model: 'Rabbit',
		mainColors: ['Black', 'White'],
		eyeColor: 'White',
		debut: ruin,
	},
	'The Mimic': {
		src: `${base}/freddle/icons/mimic.webp`,
		pronouns: 'It/Its',
		model: 'Endoskeleton',
		mainColors: 'Gray',
		eyeColor: 'Orange',
		debut: tftp1,
	},
	Theodore: {
		src: `${base}/freddle/icons/theodore.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Purple',
		eyeColor: 'Blue',
		debut: tse,
	},
	'Toy Bonnie': {
		src: `${base}/freddle/icons/toy-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Blue',
		eyeColor: 'Green',
		debut: fnaf2,
	},
	'Toy Chica': {
		src: `${base}/freddle/icons/toy-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: 'Yellow',
		eyeColor: 'Blue',
		debut: fnaf2,
	},
	'Toy Freddy': {
		src: `${base}/freddle/icons/toy-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Blue',
		debut: fnaf2,
	},
	'Toxic Springtrap': {
		src: `${base}/freddle/icons/toxic-springtrap.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Purple',
		eyeColor: ['Black', 'White'],
		debut: sd,
	},
	'Twisted Bonnie': {
		src: `${base}/freddle/icons/twisted-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Purple',
		eyeColor: 'Pink',
		debut: tto,
	},
	'Twisted Chica': {
		src: `${base}/freddle/icons/twisted-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: 'Yellow',
		eyeColor: 'Pink',
		debut: tto,
	},
	'Twisted Foxy': {
		src: `${base}/freddle/icons/twisted-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Red',
		eyeColor: 'Red',
		debut: tto,
	},
	'Twisted Freddy': {
		src: `${base}/freddle/icons/twisted-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Blue',
		debut: tto,
	},
	'Twisted Wolf': {
		src: `${base}/freddle/icons/twisted-wolf.webp`,
		pronouns: 'He/Him',
		model: 'Canine',
		mainColors: 'Gray',
		eyeColor: 'Blue',
		debut: tto,
	},
	'VR Toy Freddy': {
		src: `${base}/freddle/icons/vr-toy-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: ['Purple', 'Black'],
		eyeColor: 'Green',
		debut: sd,
	},
	'Withered Bonnie': {
		src: `${base}/freddle/icons/withered-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Blue',
		debut: fnaf2,
	},
	'Withered Chica': {
		src: `${base}/freddle/icons/withered-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: 'Yellow',
		eyeColor: 'Purple',
		debut: fnaf2,
	},
	'Withered Foxy': {
		src: `${base}/freddle/icons/withered-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Red',
		eyeColor: 'Yellow',
		debut: fnaf2,
	},
	'Withered Freddy': {
		src: `${base}/freddle/icons/withered-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Blue',
		debut: fnaf2,
	},
	'Withered Golden Freddy': {
		src: `${base}/freddle/icons/withered-golden-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Yellow',
		eyeColor: 'N/A',
		debut: fnaf2,
	},
	'Woodland Toy Freddy': {
		src: `${base}/freddle/icons/woodland-toy-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: ['Brown', 'Green'],
		eyeColor: 'Brown',
		debut: sd,
	},
	XOR: {
		src: `${base}/freddle/icons/xor.webp`,
		aliases: ['shadow dd', 'shadow dee dee'],
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: 'Gray',
		eyeColor: 'N/A',
		debut: ucn,
	},
	'Yarg Foxy': {
		src: `${base}/freddle/icons/yarg-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Red',
		eyeColor: 'Yellow',
		debut: ff2,
	},
	Yenndo: {
		src: `${base}/freddle/icons/yenndo.webp`,
		pronouns: 'He/Him',
		model: 'Endoskeleton',
		mainColors: ['Gray', 'Black'],
		eyeColor: 'Yellow',
		debut: sl,
	},
} as const;

const normal = Object.fromEntries(
	Object.entries(hard).filter(([k, v]) => {
		return (
			// Exclude book, VR, and AR characters.
			(![hw, sd].includes(v.debut) &&
				!trilogy.includes(v.debut) &&
				!frights.includes(v.debut) &&
				!tales.includes(v.debut)) ||
			// Include exceptions.
			['Glitchtrap', 'Nightmare Endo'].includes(k)
		);
	}),
);

export const sets = { normal, hard };
