import { base } from '$app/paths';

export const category = 'animatronic';

export const values = {
	FNaF1: new Date('August 8, 2014'),
	FNaF2: new Date('November 11, 2014'),
	FNaF3: new Date('March 2, 2015'),
	FNaF4: new Date('July 23, 2015'),
	'FNaF4 (HE)': new Date('October 30, 2015'),
	FW: new Date('January 21, 2016'),
	'FNaF: SL': new Date('October 7, 2016'),
	FFPS: new Date('December 4, 2017'),
	UCN: new Date('June 27, 2018'),
	'FNaF: HW': new Date('May 28, 2019'),
	'FNaF: HW (CoD)': new Date('October 23, 2019'),
	'FNaF: SD': new Date('November 25, 2019'),
	'FNaF: SB': new Date('December 16, 2021'),
	'FNaF: SB (RUIN)': new Date('July 25, 2023'),
	'FNaF: HW2': new Date('December 14, 2023'),
	'FNaF: ItP': new Date('August 7, 2024'),
	'FNaF: SotM': new Date('2025'),

	TSE: new Date('December 17, 2015'),
	TTO: new Date('June 27, 2017'),
	TFC: new Date('June 26, 2018'),

	FF1: new Date('December 26, 2019'),
	FF2: new Date('March 3, 2020'),
	FF3: new Date('May 5, 2020'),
	FF4: new Date('July 7, 2020'),
	FF5: new Date('September 1, 2020'),
	FF6: new Date('December 29, 2020'),
	FF7: new Date('March 2, 2021'),
	FF8: new Date('May 4, 2021'),
	FF9: new Date('July 6, 2021'),
	FF10: new Date('September 7, 2021'),
	FF11: new Date('November 2, 2021'),
	FF12: new Date('April 19, 2022'),

	TftP1: new Date('July 19, 2022'),
	TftP2: new Date('September 20, 2022'),
	TftP3: new Date('December 6, 2022'),
	TftP4: new Date('December 27, 2022'),
	TftP5: new Date('March 7, 2023'),
	TftP6: new Date('May 2, 2023'),
	TftP7: new Date('July 18, 2023'),
	TftP8: new Date('October 3, 2023'),
};

export const answers = {
	'8-Bit Baby': {
		src: `${base}/freddle/icons/8-bit-baby.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['White', 'Red'],
		eyeColor: 'Green',
		debut: 'FNaF: SD',
	},
	'Aeronaut Toy Freddy': {
		src: `${base}/freddle/icons/aeronaut-toy-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Blue',
		debut: 'FNaF: SD',
	},
	'Arctic Ballora': {
		src: `${base}/freddle/icons/arctic-ballora.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: 'Blue',
		eyeColor: 'Blue',
		debut: 'FNaF: SD',
	},
	'Balloon Boy': {
		src: `${base}/freddle/icons/bb.webp`,
		aliases: ['bb'],
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['Peach', 'Blue', 'Red'],
		eyeColor: 'Blue',
		debut: 'FNaF2',
	},
	Ballora: {
		src: `${base}/freddle/icons/ballora.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['White', 'Blue'],
		eyeColor: ['Pink', 'Purple'],
		debut: 'FNaF: SL',
	},
	Bidybab: {
		src: `${base}/freddle/icons/bidybab.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: 'Peach',
		eyeColor: ['Purple', 'Green'],
		debut: 'FNaF: SL',
	},
	'Big Bad Foxy': {
		src: `${base}/freddle/icons/big-bad-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: ['Red', 'Black'],
		eyeColor: ['Black', 'Red'],
		debut: 'FNaF: SD',
	},
	'Black Heart Bonnie': {
		src: `${base}/freddle/icons/black-heart-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: ['Black', 'Red'],
		eyeColor: 'Red',
		debut: 'FNaF: SD',
	},
	'Black Ice Freddy Frostbear': {
		src: `${base}/freddle/icons/black-ice-freddy-frostbear.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Blue',
		eyeColor: 'Blue',
		debut: 'FNaF: SD',
	},
	'Bon-Bon': {
		src: `${base}/freddle/icons/bon-bon.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Blue',
		eyeColor: 'Purple',
		debut: 'FNaF: SL',
	},
	Bonnet: {
		src: `${base}/freddle/icons/bonnet.webp`,
		pronouns: 'She/Her',
		model: 'Rabbit',
		mainColors: 'Pink',
		eyeColor: 'Green',
		debut: 'FNaF: SL',
	},
	Bonnie: {
		src: `${base}/freddle/icons/bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Purple',
		eyeColor: 'Purple',
		debut: 'FNaF1',
	},
	'Boulder Toy Bonnie': {
		src: `${base}/freddle/icons/boulder-toy-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: ['Gray', 'Green'],
		eyeColor: 'N/A',
		debut: 'FNaF: SD',
	},
	'Broiler Baby': {
		src: `${base}/freddle/icons/broiler-baby.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['Gray', 'Brown'],
		eyeColor: 'Red',
		debut: 'FNaF: SD',
	},
	'Bucket Bob': {
		src: `${base}/freddle/icons/bucket-bob.webp`,
		aliases: ['trash and the gang'],
		pronouns: 'He/Him',
		model: 'Bucket',
		mainColors: ['Gray', 'Brown'],
		eyeColor: 'Black',
		debut: 'FFPS',
	},
	'Burnt Foxy': {
		src: `${base}/freddle/icons/burnt-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Brown',
		eyeColor: 'Orange',
		debut: 'FNaF: HW',
	},
	Burntrap: {
		src: `${base}/freddle/icons/burntrap.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: ['Green', 'Gray'],
		eyeColor: 'Purple',
		debut: 'FNaF: SB',
	},
	'Candy Cadet': {
		src: `${base}/freddle/icons/candy-cadet.webp`,
		pronouns: 'He/Him',
		model: 'Other',
		mainColors: 'Gray',
		eyeColor: 'N/A',
		debut: 'FFPS',
	},
	'Captain Foxy': {
		src: `${base}/freddle/icons/captain-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: ['Red', 'Blue'],
		eyeColor: 'Yellow',
		debut: 'FNaF: HW (CoD)',
	},
	'Catrina Toy Chica': {
		src: `${base}/freddle/icons/catrina-toy-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: ['White', 'Red'],
		eyeColor: 'Red',
		debut: 'FNaF: SD',
	},
	'Caution Bot': {
		src: `${base}/freddle/icons/caution-bot.webp`,
		aliases: ['wet floor bot'],
		pronouns: 'It/Its',
		model: 'Wet Floor Sign',
		mainColors: 'Yellow',
		eyeColor: 'Yellow',
		debut: 'FNaF: SB',
	},
	'Charlotte Emily': {
		src: `${base}/freddle/icons/charlie.webp`,
		aliases: ['charlie'],
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: 'Peach',
		eyeColor: 'Brown',
		debut: 'TSE',
	},
	Chica: {
		src: `${base}/freddle/icons/chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: 'Yellow',
		eyeColor: 'Purple',
		debut: 'FNaF1',
	},
	'Chocolate Bonnie': {
		src: `${base}/freddle/icons/chocolate-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Brown',
		eyeColor: 'Orange',
		debut: 'FNaF: SD',
	},
	'Circus Baby': {
		src: `${base}/freddle/icons/circus-baby.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['White', 'Red'],
		eyeColor: ['Blue', 'Green'],
		debut: 'FW',
	},
	'Clockwork Ballora': {
		src: `${base}/freddle/icons/clockwork-ballora.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: 'Yellow',
		eyeColor: 'Blue',
		debut: 'FNaF: SD',
	},
	'Clockwork Minireena': {
		src: `${base}/freddle/icons/clockwork-minireena.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['Brown', 'White'],
		eyeColor: 'Green',
		debut: 'FNaF: SD',
	},
	'Clown Springtrap': {
		src: `${base}/freddle/icons/clown-springtrap.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: ['White', 'Red'],
		eyeColor: ['Blue', 'Pink'],
		debut: 'FNaF: SD',
	},
	'Coils the Birthday Clown': {
		src: `${base}/freddle/icons/coils.webp`,
		aliases: ['coils'],
		pronouns: 'It/Its',
		model: 'Humanoid',
		mainColors: ['White', 'Red', 'Green'],
		eyeColor: 'Green',
		debut: 'FF9',
	},
	'Dark Foxy': {
		src: `${base}/freddle/icons/dark-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Gray',
		eyeColor: 'White',
		debut: 'FNaF: HW',
	},
	'Dark Freddy': {
		src: `${base}/freddle/icons/dark-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Black',
		eyeColor: 'White',
		debut: 'FNaF: HW',
	},
	'Dark Water Endo': {
		src: `${base}/freddle/icons/dark-water-endo.webp`,
		pronouns: 'Unknown',
		model: 'Endoskeleton',
		mainColors: ['Blue', 'White'],
		eyeColor: 'White',
		debut: 'FNaF: SD',
	},
	'Dee Dee': {
		src: `${base}/freddle/icons/dee-dee.webp`,
		aliases: ['dd'],
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['Peach', 'Pink', 'Orange'],
		eyeColor: 'Green',
		debut: 'UCN',
	},
	'DJ Music Man': {
		src: `${base}/freddle/icons/dj-music-man.webp`,
		pronouns: 'He/Him',
		model: 'Other',
		mainColors: 'White',
		eyeColor: 'Black',
		debut: 'FNaF: SB',
	},
	Dreadbear: {
		src: `${base}/freddle/icons/dreadbear.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Gray',
		eyeColor: 'Yellow',
		debut: 'FNaF: HW (CoD)',
	},
	'Easter Bonnie': {
		src: `${base}/freddle/icons/easter-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'White',
		eyeColor: 'Blue',
		debut: 'FNaF: SD',
	},
	Eclipse: {
		src: `${base}/freddle/icons/eclipse.webp`,
		aliases: ['daycare attendant'],
		pronouns: 'They/Them',
		model: 'Humanoid',
		mainColors: ['Gray', 'Yellow', 'Blue'],
		eyeColor: ['Yellow', 'Red'],
		debut: 'FNaF: SB',
	},
	'Egg Baby': {
		src: `${base}/freddle/icons/egg-baby.webp`,
		pronouns: 'It/Its',
		model: 'Humanoid',
		mainColors: ['Peach', 'Blue'],
		eyeColor: 'Black',
		debut: 'FFPS',
	},
	'El Chip': {
		src: `${base}/freddle/icons/el-chip.webp`,
		pronouns: 'He/Him',
		model: 'Beaver',
		mainColors: 'Brown',
		eyeColor: 'Green',
		debut: 'FFPS',
	},
	Eleanor: {
		src: `${base}/freddle/icons/eleanor.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['White', 'Red'],
		eyeColor: 'Green',
		debut: 'FF1',
	},
	Electrobab: {
		src: `${base}/freddle/icons/electrobab.webp`,
		pronouns: 'They/Them',
		model: 'Humanoid',
		mainColors: 'Peach',
		eyeColor: 'Yellow',
		debut: 'FNaF: SL',
	},
	Ella: {
		src: `${base}/freddle/icons/ella.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['Peach', 'Blue', 'Pink'],
		eyeColor: 'Blue',
		debut: 'TSE',
	},
	'Endo-01': {
		src: `${base}/freddle/icons/endo-01.webp`,
		aliases: ['bare endo'],
		pronouns: 'it/its',
		model: 'Endoskeleton',
		mainColors: 'Gray',
		eyeColor: 'Blue',
		debut: 'FNaF1',
	},
	'Endo-02': {
		src: `${base}/freddle/icons/endo-02.webp`,
		pronouns: 'it/its',
		model: 'Endoskeleton',
		mainColors: 'Gray',
		eyeColor: 'Blue',
		debut: 'FNaF2',
	},
	Ennard: {
		src: `${base}/freddle/icons/ennard.webp`,
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['Gray', 'White'],
		eyeColor: 'Blue',
		debut: 'FNaF: SL',
	},
	Fetch: {
		src: `${base}/freddle/icons/fetch.webp`,
		pronouns: 'He/Him',
		model: 'Canine',
		mainColors: 'Gray',
		eyeColor: 'Orange',
		debut: 'FF2',
	},
	'Firework Freddy': {
		src: `${base}/freddle/icons/firework-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: ['Brown', 'Blue', 'Red'],
		eyeColor: 'Blue',
		debut: 'FNaF: SD',
	},
	'Flamethrower Endo': {
		src: `${base}/freddle/icons/flamethrower-endo.webp`,
		pronouns: 'It/Its',
		model: 'Endoskeleton',
		mainColors: ['Yellow', 'Brown'],
		eyeColor: 'Blue',
		debut: 'FNaF: SD',
	},
	'Flaming Springtrap': {
		src: `${base}/freddle/icons/flaming-springtrap.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: ['Black', 'Orange'],
		eyeColor: 'Red',
		debut: 'FNaF: SD',
	},
	Foxy: {
		src: `${base}/freddle/icons/foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Red',
		eyeColor: 'Yellow',
		debut: 'FNaF1',
	},
	Fredbear: {
		src: `${base}/freddle/icons/fredbear.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Yellow',
		eyeColor: ['Black', 'White'],
		debut: 'FNaF3',
	},
	Freddles: {
		src: `${base}/freddle/icons/freddles.webp`,
		pronouns: 'They/Them',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: ['Black', 'White'],
		debut: 'FNaF4',
	},
	'Freddy Fazbear': {
		src: `${base}/freddle/icons/freddy.webp`,
		aliases: ['har har har har har', 'freddy'],
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Blue',
		debut: 'FNaF1',
	},
	'Frost Plushtrap': {
		src: `${base}/freddle/icons/frost-plushtrap.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Blue',
		eyeColor: 'Blue',
		debut: 'FNaF: SD',
	},
	'Frostbite Balloon Boy': {
		src: `${base}/freddle/icons/frostbite-bb.webp`,
		aliases: ['blizzard balloon boy', 'blizzard bb', 'frostbite bb'],
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['White', 'Blue'],
		eyeColor: 'N/A',
		debut: 'FNaF: SD',
	},
	'Fruit Punch Clown': {
		src: `${base}/freddle/icons/fruit-punch-clown.webp`,
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['White', 'Red', 'Purple'],
		eyeColor: 'Green',
		debut: 'FFPS',
	},
	'Funtime Chica': {
		src: `${base}/freddle/icons/funtime-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: ['White', 'Pink'],
		eyeColor: 'Pink',
		debut: 'FFPS',
	},
	'Funtime Foxy': {
		src: `${base}/freddle/icons/funtime-foxy.webp`,
		pronouns: 'Yes',
		model: 'Fox',
		mainColors: ['White', 'Pink'],
		eyeColor: 'Yellow',
		debut: 'FW',
	},
	'Funtime Freddy': {
		src: `${base}/freddle/icons/funtime-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: ['White', 'Purple'],
		eyeColor: 'Blue',
		debut: 'FNaF: SL',
	},
	'Glamrock Bonnie': {
		src: `${base}/freddle/icons/glamrock-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: ['Blue', 'Red'],
		eyeColor: 'Red',
		debut: 'FNaF: SB (RUIN)',
	},
	'Glamrock Chica': {
		src: `${base}/freddle/icons/glamrock-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: ['White', 'Purple', 'Green'],
		eyeColor: 'Blue',
		debut: 'FNaF: SB',
	},
	'Glamrock Endo': {
		src: `${base}/freddle/icons/glamrock-endo.webp`,
		pronouns: 'He/Him',
		model: 'Endoskeleton',
		mainColors: 'Gray',
		eyeColor: 'Red',
		debut: 'FNaF: SB',
	},
	'Glamrock Freddy': {
		src: `${base}/freddle/icons/glamrock-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Orange',
		eyeColor: 'Blue',
		debut: 'FNaF: SB',
	},
	'Glamrock Mr. Hippo': {
		src: `${base}/freddle/icons/glamrock-mr-hippo.webp`,
		pronouns: 'He/Him',
		model: 'Hippo',
		mainColors: 'Purple',
		eyeColor: 'Blue',
		debut: 'FNaF: SB',
	},
	Glitchtrap: {
		src: `${base}/freddle/icons/glitchtrap.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Brown',
		eyeColor: 'Purple',
		debut: 'FNaF: HW',
	},
	'Golden Freddy': {
		src: `${base}/freddle/icons/golden-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Yellow',
		eyeColor: 'N/A',
		debut: 'FNaF1',
	},
	'Grimm Foxy': {
		src: `${base}/freddle/icons/grimm-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Orange',
		eyeColor: 'Orange',
		debut: 'FNaF: HW (CoD)',
	},
	HandUnit: {
		src: `${base}/freddle/icons/hand-unit.webp`,
		pronouns: 'He/Him',
		model: 'Other',
		mainColors: 'Yellow',
		eyeColor: 'Black',
		debut: 'FNaF: SL',
	},
	'Happy Frog': {
		src: `${base}/freddle/icons/happy-frog.webp`,
		pronouns: 'She/Her',
		model: 'Frog',
		mainColors: ['Green', 'Yellow'],
		eyeColor: 'Pink',
		debut: 'FFPS',
	},
	'Heartsick Baby': {
		src: `${base}/freddle/icons/heartsick-baby.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['Purple', 'White'],
		eyeColor: 'Red',
		debut: 'FNaF: SD',
	},
	Helpi: {
		src: `${base}/freddle/icons/helpi.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mairColor: ['Purple', 'Blue'],
		eyeColor: 'Blue',
		debut: 'FNaF: SB (RUIN)',
	},
	Helpy: {
		src: `${base}/freddle/icons/helpy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mairColor: ['White', 'Purple'],
		eyeColor: 'Blue',
		debut: 'FFPS',
	},
	'Highscore Toy Chica': {
		src: `${base}/freddle/icons/highscore-toy-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: ['Blue', 'Black'],
		eyeColor: 'Yellow',
		debut: 'FNaF: SD',
	},
	'Jack-O-Bonnie': {
		src: `${base}/freddle/icons/jack-o-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: ['Orange', 'Brown'],
		eyeColor: 'N/A',
		debut: 'FNaF4 (HE)',
	},
	'Jack-O-Chica': {
		src: `${base}/freddle/icons/jack-o-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: ['Orange', 'Brown'],
		eyeColor: 'N/A',
		debut: 'FNaF4 (HE)',
	},
	'Jetpack Balloon Boy': {
		src: `${base}/freddle/icons/jetpack-balloon-boy.webp`,
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: 'Brown',
		eyeColor: 'Orange',
		debut: 'FNaF: SD',
	},
	JJ: {
		src: `${base}/freddle/icons/jj.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['Peach', 'Blue', 'Purple'],
		eyeColor: 'Pink',
		debut: 'FNaF2',
	},
	Lefty: {
		src: `${base}/freddle/icons/lefty.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Black',
		eyeColor: ['Yellow', 'Black'],
		debut: 'FFPS',
	},
	'Lemonade Clown': {
		src: `${base}/freddle/icons/lemonade-clown.webp`,
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['White', 'Purple', 'Orange'],
		eyeColor: 'Blue',
		debut: 'FFPS',
	},
	'Liberty Chica': {
		src: `${base}/freddle/icons/liberty-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: 'Blue',
		eyeColor: 'Green',
		debut: 'FNaF: SD',
	},
	'Little Red Chica': {
		src: `${base}/freddle/icons/little-red-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: ['Red', 'White'],
		eyeColor: 'Yellow',
		debut: 'FNaF: SD',
	},
	Lolbit: {
		src: `${base}/freddle/icons/lolbit.webp`,
		pronouns: 'they/them',
		model: 'Fox',
		mainColors: ['White', 'Orange', 'Purple'],
		eyeColor: 'White',
		debut: 'FNaF: SL',
	},
	'Lonely Freddy': {
		src: `${base}/freddle/icons/lonely-freddy.webp`,
		pronouns: 'it/its',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Blue',
		debut: 'FF2',
	},
	'Lucky Boy': {
		src: `${base}/freddle/icons/lucky-boy.webp`,
		pronouns: 'He/Him',
		model: 'Blue',
		mainColors: ['Peach', 'Blue', 'Red'],
		eyeColor: 'Blue',
		debut: 'FF8',
	},
	'Magician Mangle': {
		src: `${base}/freddle/icons/magician-mangle.webp`,
		pronouns: 'Yes',
		model: 'Fox',
		mainColors: 'White',
		eyeColor: ['Blue', 'Yellow'],
		debut: 'FNaF: SD',
	},
	Mangle: {
		src: `${base}/freddle/icons/mangle.webp`,
		pronouns: 'Yes',
		model: 'Fox',
		mainColors: ['White', 'Pink'],
		eyeColor: 'Yellow',
		debut: 'FNaF2',
	},
	'Mask Bot': {
		src: `${base}/freddle/icons/mask-bot.webp`,
		pronouns: 'Unknown',
		model: 'Humanoid',
		mainColors: ['White', 'Yellow'],
		eyeColor: 'Black',
		debut: 'FNaF: SB (RUIN)',
	},
	'Melted Chocolate Bonnie': {
		src: `${base}/freddle/icons/melted-chocolate-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Brown',
		eyeColor: 'Orange',
		debut: 'FNaF: SD',
	},
	'Mini Music Man': {
		src: `${base}/freddle/icons/mini-music-man.webp`,
		pronouns: 'He/Him',
		model: 'Other',
		mainColors: ['White', 'Purple', 'Pink'],
		eyeColor: 'Black',
		debut: 'FNaF: SB',
	},
	Minireena: {
		src: `${base}/freddle/icons/minireena.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['Brown', 'White'],
		eyeColor: 'Yellow',
		debut: 'FNaF: SL',
	},
	'Molten Freddy': {
		src: `${base}/freddle/icons/molten-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: ['Gray', 'White', 'Brown'],
		eyeColor: 'Orange',
		debut: 'FFPS',
	},
	'Montgomery Gator': {
		src: `${base}/freddle/icons/monty.webp`,
		aliases: ['monty'],
		pronouns: 'He/Him',
		model: 'Alligator',
		mainColors: ['Green', 'Purple'],
		eyeColor: 'Red',
		debut: 'FNaF: SB',
	},
	Moon: {
		src: `${base}/freddle/icons/moon.webp`,
		aliases: ['daycare attendant'],
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['Blue', 'White', 'Black'],
		eyeColor: 'Red',
		debut: 'FNaF: SB',
	},
	'Mr. Can-Do': {
		src: `${base}/freddle/icons/mr-can-do.webp`,
		aliases: ['trash and the gang'],
		pronouns: 'He/Him',
		model: 'Other',
		mainColors: ['Red', 'Gray'],
		eyeColor: 'Black',
		debut: 'FFPS',
	},
	'Mr. Hippo': {
		src: `${base}/freddle/icons/mr-hippo.webp`,
		pronouns: 'He/Him',
		model: 'Hippo',
		mainColors: 'Purple',
		eyeColor: 'Blue',
		debut: 'FFPS',
	},
	'Mr. Hugs': {
		src: `${base}/freddle/icons/mr-hugs.webp`,
		aliases: ['trash and the gang'],
		pronouns: 'He/Him',
		model: 'Vacuum',
		mainColors: ['Green', 'Brown'],
		eyeColor: 'Black',
		debut: 'FFPS',
	},
	'Music Man': {
		src: `${base}/freddle/icons/music-man.webp`,
		pronouns: 'He/Him',
		model: 'Other',
		mainColors: ['White', 'Purple', 'Pink'],
		eyeColor: 'Black',
		debut: 'FFPS',
	},
	'Mystic Hippo': {
		src: `${base}/freddle/icons/mystic-hippo.webp`,
		pronouns: 'She/Her',
		model: 'Hippo',
		mainColors: 'Purple',
		eyeColor: 'Blue',
		debut: 'FNaF: HW2',
	},
	'Nedd Bear': {
		src: `${base}/freddle/icons/nedd-bear.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Green',
		debut: 'FFPS',
	},
	'Neon Bonnie': {
		src: `${base}/freddle/icons/neon-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: ['Black'],
		eyeColor: 'Blue',
		debut: 'FNaF: HW',
	},
	'Neon Chica': {
		src: `${base}/freddle/icons/neon-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: ['Black'],
		eyeColor: 'Green',
		debut: 'FNaF: HW',
	},
	Nightmare: {
		src: `${base}/freddle/icons/nightmare.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Black',
		eyeColor: 'Red',
		debut: 'FNaF4',
	},
	'Nightmare Balloon Boy': {
		src: `${base}/freddle/icons/nightmare-bb.webp`,
		aliases: ['nightmare bb'],
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['Peach', 'Red', 'Purple'],
		eyeColor: 'Red',
		debut: 'FNaF4 (HE)',
	},
	'Nightmare Bonnie': {
		src: `${base}/freddle/icons/nightmare-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Blue',
		eyeColor: ['Purple', 'Yellow'],
		debut: 'FNaF4',
	},
	'Nightmare Chica': {
		src: `${base}/freddle/icons/nightmare-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: 'Yellow',
		eyeColor: ['Blue', 'Red'],
		debut: 'FNaF4',
	},
	'Nightmare Endo': {
		src: `${base}/freddle/icons/nightmare-endo.webp`,
		pronouns: 'Unknown',
		model: 'Endoskeleton',
		mainColors: 'Gray',
		eyeColor: 'Red',
		debut: 'FNaF: HW',
	},
	'Nightmare Foxy': {
		src: `${base}/freddle/icons/nightmare-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Red',
		eyeColor: 'Orange',
		debut: 'FNaF4',
	},
	'Nightmare Fredbear': {
		src: `${base}/freddle/icons/nightmare-fredbear.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Yellow',
		eyeColor: 'Red',
		debut: 'FNaF4',
	},
	'Nightmare Freddy': {
		src: `${base}/freddle/icons/nightmare-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Orange',
		debut: 'FNaF4',
	},
	'Nightmare Mangle': {
		src: `${base}/freddle/icons/nightmare-mangle.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: ['White', 'Pink'],
		eyeColor: 'Yellow',
		debut: 'FNaF4 (HE)',
	},
	Nightmarionne: {
		src: `${base}/freddle/icons/nightmarionne.webp`,
		aliases: ['nightmare puppet'],
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['Black', 'White'],
		eyeColor: ['Black', 'White'],
		debut: 'FNaF4 (HE)',
	},
	'Nightmarionne S.T.A.F.F. Bot': {
		src: `${base}/freddle/icons/nightmarionne-staff-bot.webp`,
		pronouns: 'Unknown',
		model: 'Humanoid',
		mainColors: ['White', 'Black'],
		eyeColor: 'White',
		debut: 'FNaF4 (HE)',
	},
	'No. 1 Crate': {
		src: `${base}/freddle/icons/no-1-crate.webp`,
		aliases: ['trash and the gang'],
		pronouns: 'She/Her',
		model: 'Crate',
		mainColors: ['Blue', 'Red'],
		eyeColor: 'Black',
		debut: 'FFPS',
	},
	'Old Man Consequences': {
		src: `${base}/freddle/icons/omc.webp`,
		aliases: ['omc'],
		pronouns: 'He/Him',
		model: 'Alligator',
		mainColors: 'Red',
		eyeColor: 'N/A',
		debut: 'FW',
	},
	'Orville Elephant': {
		src: `${base}/freddle/icons/orville-elephant.webp`,
		pronouns: 'He/Him',
		model: 'Elephant',
		mainColors: 'Orange',
		eyeColor: 'Blue',
		debut: 'FFPS',
	},
	'Pan Stan': {
		src: `${base}/freddle/icons/pan-stan.webp`,
		aliases: ['trash and the gang'],
		pronouns: 'He/Him',
		model: 'Pan',
		mainColors: ['Gray', 'Brown'],
		eyeColor: 'Black',
		debut: 'FFPS',
	},
	'Party Freddy': {
		src: `${base}/freddle/icons/party-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: ['Black', 'Red'],
		eyeColor: 'Black',
		debut: 'FNaF: HW',
	},
	'Phantom Balloon Boy': {
		src: `${base}/freddle/icons/phantom-bb.webp`,
		aliases: ['phantom bb'],
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: 'Green',
		eyeColor: ['Black', 'White'],
		debut: 'FNaF3',
	},
	'Phantom Chica': {
		src: `${base}/freddle/icons/phantom-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: 'Green',
		eyeColor: ['Black', 'White'],
		debut: 'FNaF3',
	},
	'Phantom Foxy': {
		src: `${base}/freddle/icons/phantom-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Green',
		eyeColor: ['Black', 'White'],
		debut: 'FNaF3',
	},
	'Phantom Freddy': {
		src: `${base}/freddle/icons/phantom-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Green',
		eyeColor: ['Black', 'White'],
		debut: 'FNaF3',
	},
	'Phantom Mangle': {
		src: `${base}/freddle/icons/phantom-mangle.webp`,
		pronouns: 'Yes',
		model: 'Fox',
		mainColors: 'Green',
		eyeColor: ['Black', 'White'],
		debut: 'FNaF3',
	},
	'Phantom Puppet': {
		src: `${base}/freddle/icons/phantom-puppet.webp`,
		aliases: ['phantom marionette'],
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: 'Green',
		eyeColor: ['Black', 'White'],
		debut: 'FNaF3',
	},
	Pigpatch: {
		src: `${base}/freddle/icons/pigpatch.webp`,
		pronouns: 'He/Him',
		model: 'Pig',
		mainColors: 'Pink',
		eyeColor: ['Green', 'Blue'],
		debut: 'FFPS',
	},
	'Piranha Plushtrap': {
		src: `${base}/freddle/icons/piranha-plushtrap.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Gray',
		eyeColor: 'Blue',
		debut: 'FNaF: SD',
	},
	Plushtrap: {
		src: `${base}/freddle/icons/plushtrap.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: ['Green', 'Brown'],
		eyeColor: 'Black',
		debut: 'FNaF4',
	},
	'Prize King': {
		src: `${base}/freddle/icons/prize-king.webp`,
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['Yellow'],
		eyeColor: 'Green',
		debut: 'FFPS',
	},
	'The Puppet': {
		src: `${base}/freddle/icons/puppet.webp`,
		aliases: ['the marionette'],
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['Black', 'White'],
		eyeColor: ['Black', 'White'],
		debut: 'FNaF2',
	},
	'Radioactive Foxy': {
		src: `${base}/freddle/icons/radioactive-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Green',
		eyeColor: 'Yellow',
		debut: 'FNaF: SD',
	},
	Ralpho: {
		src: `${base}/freddle/icons/ralpho.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Orange',
		eyeColor: 'Blue',
		debut: 'FF5',
	},
	'Ringmaster Foxy': {
		src: `${base}/freddle/icons/ringmaster-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: ['White', 'Red'],
		eyeColor: 'Yellow',
		debut: 'FNaF: SD',
	},
	'Rockstar Bonnie': {
		src: `${base}/freddle/icons/rockstar-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Blue',
		eyeColor: 'Green',
		debut: 'FFPS',
	},
	'Rockstar Chica': {
		src: `${base}/freddle/icons/rockstar-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: 'Yellow',
		eyeColor: 'Pink',
		debut: 'FFPS',
	},
	'Rockstar Foxy': {
		src: `${base}/freddle/icons/rockstar-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Red',
		eyeColor: 'Orange',
		debut: 'FFPS',
	},
	'Rockstar Freddy': {
		src: `${base}/freddle/icons/rockstar-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Blue',
		debut: 'FFPS',
	},
	'Roxanne Wolf': {
		src: `${base}/freddle/icons/roxy.webp`,
		aliases: ['roxy'],
		pronouns: 'She/Her',
		model: 'Canine',
		mainColors: ['Gray', 'Purple'],
		eyeColor: 'Yellow',
		debut: 'FNaF: SB',
	},
	RWQFSFASXC: {
		src: `${base}/freddle/icons/rwqfsfasxc.webp`,
		aliases: ['shadow bonnie'],
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Black',
		eyeColor: 'White',
		debut: 'FNaF2',
	},
	'Scorching Chica': {
		src: `${base}/freddle/icons/scorching-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: ['Black', 'Red'],
		eyeColor: 'Orange',
		debut: 'FNaF: SD',
	},
	'Scrap Baby': {
		src: `${base}/freddle/icons/scrap-baby.webp`,
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: ['Orange', 'White'],
		eyeColor: 'Green',
		debut: 'FFPS',
	},
	Scraptrap: {
		src: `${base}/freddle/icons/scraptrap.webp`,
		aliases: ['william afton'],
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Green',
		eyeColor: 'Gray',
		debut: 'FFPS',
	},
	'Security Puppet': {
		src: `${base}/freddle/icons/security-puppet.webp`,
		pronouns: 'It/Its',
		model: 'Humanoid',
		mainColors: ['Black', 'White'],
		eyeColor: 'Yellow',
		debut: 'FFPS',
	},
	'Serpent Mangle': {
		src: `${base}/freddle/icons/serpent-mangle.webp`,
		pronouns: 'Yes',
		model: 'Fox',
		mainColors: ['Green', 'Yellow', 'Red'],
		eyeColor: 'Yellow',
		debut: 'FNaF: SD',
	},
	'Shadow Freddy': {
		src: `${base}/freddle/icons/shadow-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Purple',
		eyeColor: 'White',
		debut: 'FNaF2',
	},
	'Shadow Mangle': {
		src: `${base}/freddle/icons/shadow-mangle.webp`,
		pronouns: 'yes',
		model: 'Fox',
		mainColors: 'Black',
		eyeColor: 'Yellow',
		debut: 'FNaF: HW',
	},
	'Shamrock Freddy': {
		src: `${base}/freddle/icons/shamrock-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Green',
		eyeColor: 'Green',
		debut: 'FNaF: SD',
	},
	'Spring Bonnie': {
		src: `${base}/freddle/icons/spring-bonnie.webp`,
		pronouns: 'They/Them',
		model: 'Rabbit',
		mainColors: 'Yellow',
		eyeColor: 'Green',
		debut: 'FNaF3',
	},
	Springtrap: {
		src: `${base}/freddle/icons/springtrap.webp`,
		aliases: ['william afton'],
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Green',
		eyeColor: 'Gray',
		debut: 'FNaF3',
	},
	Stanley: {
		src: `${base}/freddle/icons/stanley.webp`,
		pronouns: 'He/Him',
		model: 'Other',
		mainColors: 'White',
		eyeColor: 'Purple',
		debut: 'TSE',
	},
	'The Stitchwraith': {
		src: `${base}/freddle/icons/stitchwraith.webp`,
		pronouns: 'It/Its',
		model: 'Endoskeleton',
		mainColors: ['Black', 'White'],
		eyeColor: ['Black', 'White'],
		debut: 'FF1',
	},
	Sun: {
		src: `${base}/freddle/icons/sun.webp`,
		aliases: ['daycare attendant'],
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: 'Yellow',
		eyeColor: 'White',
		debut: 'FNaF: SB',
	},
	'Sunken Toy Bonnie': {
		src: `${base}/freddle/icons/sunken-toy-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: ['Brown', 'Green'],
		eyeColor: ['Blue', 'Purple'],
		debut: 'FNaF: SD',
	},
	'Swamp Balloon Boy': {
		src: `${base}/freddle/icons/swamp-bb.webp`,
		aliases: ['swamp bb'],
		pronouns: 'He/Him',
		model: 'Humanoid',
		mainColors: ['Brown', 'Green', 'Gray'],
		eyeColor: 'N/A',
		debut: 'FNaF: SD',
	},
	'System Error Toy Bonnie': {
		src: `${base}/freddle/icons/system-error-toy-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Red',
		eyeColor: 'Yellow',
		debut: 'FNaF: SD',
	},
	'Tag-Along Freddy': {
		src: `${base}/freddle/icons/tag-along-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Blue',
		debut: 'FF7',
	},
	Tangle: {
		src: `${base}/freddle/icons/tangle.webp`,
		aliases: ['the blob'],
		pronouns: 'It/Its',
		model: 'Bear',
		mainColors: 'Gray',
		eyeColor: 'Red',
		debut: 'FNaF: SB',
	},
	'The Curse': {
		src: `${base}/freddle/icons/the-curse.webp`,
		pronouns: 'he/him',
		model: 'Rabbit',
		mainColors: ['Blue', 'Yellow', 'Green'],
		eyeColor: 'Yellow',
		debut: 'FNaF: SD',
	},
	'The Entity': {
		src: `${base}/freddle/icons/mxes.webp`,
		aliases: ['m.x.e.s.', 'mxes'],
		pronouns: 'They/Them',
		model: 'Rabbit',
		mainColors: ['Black', 'White'],
		eyeColor: 'White',
		debut: 'FNaF: SB (RUIN)',
	},
	'The Mimic': {
		src: `${base}/freddle/icons/mimic.webp`,
		pronouns: 'It/Its',
		model: 'Endoskeleton',
		mainColors: 'Gray',
		eyeColor: 'Orange',
		debut: 'TftP1',
	},
	Theodore: {
		src: `${base}/freddle/icons/theodore.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Purple',
		eyeColor: 'Blue',
		debut: 'TSE',
	},
	'Toy Bonnie': {
		src: `${base}/freddle/icons/toy-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Blue',
		eyeColor: 'Green',
		debut: 'FNaF2',
	},
	'Toy Chica': {
		src: `${base}/freddle/icons/toy-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: 'Yellow',
		eyeColor: 'Blue',
		debut: 'FNaF2',
	},
	'Toy Freddy': {
		src: `${base}/freddle/icons/toy-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Blue',
		debut: 'FNaF2',
	},
	'Toxic Springtrap': {
		src: `${base}/freddle/icons/toxic-springtrap.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Purple',
		eyeColor: ['Black', 'White'],
		debut: 'FNaF: SD',
	},
	'Twisted Bonnie': {
		src: `${base}/freddle/icons/twisted-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Rabbit',
		mainColors: 'Purple',
		eyeColor: 'Pink',
		debut: 'TTO',
	},
	'Twisted Chica': {
		src: `${base}/freddle/icons/twisted-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: 'Yellow',
		eyeColor: 'Pink',
		debut: 'TTO',
	},
	'Twisted Foxy': {
		src: `${base}/freddle/icons/twisted-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Red',
		eyeColor: 'Red',
		debut: 'TTO',
	},
	'Twisted Freddy': {
		src: `${base}/freddle/icons/twisted-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Blue',
		debut: 'TTO',
	},
	'Twisted Wolf': {
		src: `${base}/freddle/icons/twisted-wolf.webp`,
		pronouns: 'He/Him',
		model: 'Canine',
		mainColors: 'Gray',
		eyeColor: 'Blue',
		debut: 'TTO',
	},
	'VR Toy Freddy': {
		src: `${base}/freddle/icons/vr-toy-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: ['Purple', 'Black'],
		eyeColor: 'Green',
		debut: 'FNaF: SD',
	},
	'Withered Bonnie': {
		src: `${base}/freddle/icons/withered-bonnie.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Blue',
		debut: 'FNaF2',
	},
	'Withered Chica': {
		src: `${base}/freddle/icons/withered-chica.webp`,
		pronouns: 'She/Her',
		model: 'Chicken',
		mainColors: 'Yellow',
		eyeColor: 'Purple',
		debut: 'FNaF2',
	},
	'Withered Foxy': {
		src: `${base}/freddle/icons/withered-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Red',
		eyeColor: 'Yellow',
		debut: 'FNaF2',
	},
	'Withered Freddy': {
		src: `${base}/freddle/icons/withered-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Brown',
		eyeColor: 'Blue',
		debut: 'FNaF2',
	},
	'Withered Golden Freddy': {
		src: `${base}/freddle/icons/withered-golden-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: 'Yellow',
		eyeColor: 'N/A',
		debut: 'FNaF2',
	},
	'Woodland Toy Freddy': {
		src: `${base}/freddle/icons/woodland-toy-freddy.webp`,
		pronouns: 'He/Him',
		model: 'Bear',
		mainColors: ['Brown', 'Green'],
		eyeColor: 'Brown',
		debut: 'FNaF: SD',
	},
	XOR: {
		src: `${base}/freddle/icons/xor.webp`,
		aliases: ['shadow dd', 'shadow dee dee'],
		pronouns: 'She/Her',
		model: 'Humanoid',
		mainColors: 'Gray',
		eyeColor: 'N/A',
		debut: 'UCN',
	},
	'Yarg Foxy': {
		src: `${base}/freddle/icons/yarg-foxy.webp`,
		pronouns: 'He/Him',
		model: 'Fox',
		mainColors: 'Red',
		eyeColor: 'Yellow',
		debut: 'FF2',
	},
	Yenndo: {
		src: `${base}/freddle/icons/yenndo.webp`,
		pronouns: 'He/Him',
		model: 'Endoskeleton',
		mainColors: ['Gray', 'Black'],
		eyeColor: 'Yellow',
		debut: 'FNaF: SL',
	},
} as const;
